---
driver_plugin: vagrant

platforms:
- name: centos-5.11
- name: centos-6.6
- name: centos-7.0
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04

suites:
- name: default
  run_list:
  - recipe[couchdb]
- name: source
  run_list:
  - recipe[build-essential]
  - recipe[couchdb::source]
  attributes: {}
- name: resource_provider
  run_list:
  - recipe[couchdb-test]
